exports.map = {
    'keypress' : 'cursor.keypress',
    'enter' : 'cursor.newline',
    'delete' : 'cursor.delete_forward',
    'backspace' : 'cursor.delete_backward',
    'leftarrow' : 'cursor.left',
    'rightarrow' : 'cursor.right',
    'uparrow' : 'cursor.up',
    'downarrow' : 'cursor.down',
    'shift-leftarrow' : 'cursor.select_left',
    'shift-rightarrow' : 'cursor.select_right',
    'shift-uparrow' : 'cursor.select_up',
    'shift-downarrow' : 'cursor.select_down',
    'mouse0-down' : 'cursors.start_selection',
    'mouse-move' : 'cursors.set_selection',
    'mouse0-up' : 'cursors.end_selection',
};