exports.map = {
    'keypress' : 'cursor.keypress',
    'enter' : 'cursor.newline',
    'delete' : 'cursor.delete_forward',
    'backspace' : 'cursor.delete_backward',
    'left' : 'cursor.left',
    'right' : 'cursor.right',
    'up' : 'cursor.up',
    'down' : 'cursor.down',
    'shift-left' : 'cursor.select_left',
    'shift-right' : 'cursor.select_right',
    'shift-up' : 'cursor.select_up',
    'shift-down' : 'cursor.select_down',
    'mouse0-down' : 'cursors.start_selection',
    'mouse-move' : 'cursors.set_selection',
    'mouse0-up' : 'cursors.end_selection',
};